# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cb0c69d317b2bf5c67efbf665bd955f4f86695abbe1f0197b85b84b25076c814b3e423b75f95688eff0c64e796db9ad582b0fe5c18dd041c88761889a07f994a

test:
  secret_key_base: c2b07771dfaf705e4e064feac64b90e8d5d805efdc8a4a90a2e9aef60a7f5ec7a080428f1b3b369a2726451ca9aa4d6fb2cc732060e71fa604a7bd5d070bca65

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
